<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DocumentSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('documents')->delete();
        DB::table('documents')->insert([
            [
                'doc_id' => 'DOC01',
                'title' => 'Sách Giáo Lý Khối Khai Tâm (Bản Chuẩn GP. Phú Cường)',
                'category' => 'Giáo Trình',
                'format' => 'PDF',
                'target' => 'Khối Khai Tâm (Lớp Dự Bị, KT1, KT2)',
                'size' => '4.2 MB',
                'author' => 'Ủy Ban Giáo Lý GP Phú Cường',
                'downloads' => 320,
                'desc' => 'Giáo trình tranh ảnh đầy đủ màu sắc dành cho các em 6-8 tuổi bắt đầu làm quen với Chúa Giêsu, lời cầu nguyện và các nhân vật Kinh Thánh.',
                'content' => 'Tài liệu gồm 24 bài học căn bản về Thiên Chúa Tình Yêu, Chúa Giêsu Bạn Của Trẻ Thơ, Đức Mẹ Maria và những kinh nguyện đầu đời.',
                'file_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'doc_id' => 'DOC02',
                'title' => 'Sách Giáo Lý Đến Bàn Tiệc Thánh - Khối Rước Lễ',
                'category' => 'Giáo Trình',
                'format' => 'PDF',
                'target' => 'Khối Rước Lễ (RL1, RL2, RL3)',
                'size' => '5.8 MB',
                'author' => 'Ủy Ban Giáo Lý Đức Tin',
                'downloads' => 415,
                'desc' => 'Tài liệu chuẩn bị tâm hồn cho các em xưng tội và rước lễ lần đầu, gồm các bí tích Hòa Giải và Thánh Thể.',
                'content' => 'Tài liệu gồm 30 bài học chuyên sâu về Bí Tích Hòa Giải, Bí Tích Thánh Thể, 10 Điều Răn và 6 Điều Răn Hội Thánh.',
                'file_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'doc_id' => 'DOC03',
                'title' => 'Sách Giáo Lý Lớn Lên Trong Chúa Thánh Thần - Khối Thêm Sức',
                'category' => 'Giáo Trình',
                'format' => 'PDF',
                'target' => 'Khối Thêm Sức (TS1, TS2, TS3)',
                'size' => '6.1 MB',
                'author' => 'Ủy Ban Giáo Lý Đức Tin',
                'downloads' => 380,
                'desc' => 'Giáo trình bồi dưỡng đức tin và 7 ơn Chúa Thánh Thần giúp các em sẵn sàng lãnh nhận Bí tích Thêm Sức.',
                'content' => 'Gồm 32 bài học về Chúa Thánh Thần, Hội Thánh, Phụng Vụ, 7 Ơn Chúa Thánh Thần và Đời Sống Đức Tin Trưởng Thành.',
                'file_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'doc_id' => 'DOC04',
                'title' => 'Sách Giáo Lý Sống Đạo Giữa Đời - Khối Bao Đồng',
                'category' => 'Giáo Trình',
                'format' => 'PDF',
                'target' => 'Khối Bao Đồng (BD1, BD2, BD3)',
                'size' => '7.0 MB',
                'author' => 'Ủy Ban Giáo Lý GP Phú Cường',
                'downloads' => 290,
                'desc' => 'Giáo trình tuyên xưng đức tin, sống đạo và đối thoại giữa người Kitô hữu trong xã hội hiện đại.',
                'content' => 'Gồm 36 bài học về Luân Lý Công Giáo, Nhân Bản Kitô Giáo, Lương Tâm, Tội Lỗi và Ơn Cứu Độ.',
                'file_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'doc_id' => 'DOC05',
                'title' => 'Sách Giáo Lý Hành Trang Vào Đời - Khối Vào Đời',
                'category' => 'Giáo Trình',
                'format' => 'PDF',
                'target' => 'Khối Vào Đời (VD1, VD2)',
                'size' => '6.5 MB',
                'author' => 'Ủy Ban Giáo Lý Đức Tin',
                'downloads' => 260,
                'desc' => 'Hành trang định hướng ơn gọi, hôn nhân gia đình, đạo đức nghề nghiệp và sứ vụ tông đồ giáo dân.',
                'content' => 'Gồm 28 bài học định hướng tương lai, tình yêu - hôn nhân Kitô giáo, trách nhiệm xã hội và ơn gọi đời sống.',
                'file_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'doc_id' => 'DOC06',
                'title' => 'Nội Quy & Sổ Tay Huynh Trưởng Thiếu Nhi Thánh Thể VN',
                'category' => 'Sổ Tay',
                'format' => 'PDF',
                'target' => 'Dành Cho GLV & Huynh Trưởng',
                'size' => '3.5 MB',
                'author' => 'Tổng Liên Đoàn TNTT Việt Nam',
                'downloads' => 510,
                'desc' => 'Cẩm nang toàn diện về phương pháp tự nhiên, siêu nhiên, hiệu lệnh còi cờ, nghi thức chào cờ và linh đạo TNTT.',
                'content' => 'Quy định đầy đủ về đồng phục, cấp bậc, nghi thức tuyên hứa, quản lý đoàn sinh và điều hành sa mạc huấn luyện.',
                'file_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'doc_id' => 'DOC07',
                'title' => 'Sổ Tay Kỹ Năng & Trò Chơi Sinh Hoạt Thiếu Nhi',
                'category' => 'Sổ Tay',
                'format' => 'DOCX',
                'target' => 'Dành Cho GLV Đứng Lớp',
                'size' => '2.1 MB',
                'author' => 'Ban Kỹ Năng Xứ Đoàn Tân Mỹ',
                'downloads' => 440,
                'desc' => 'Tổng hợp hơn 150 trò chơi vòng tròn, băng reo, trò chơi Kinh Thánh, gút dây và mật thư ứng dụng.',
                'content' => 'Bộ sưu tập trò chơi sinh hoạt giáo lý theo từng chủ đề bài học, giúp giờ học luôn hào hứng và sôi nổi.',
                'file_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'doc_id' => 'DOC08',
                'title' => 'Tuyển Tập Bài Hát Sinh Hoạt & Nghi Thức TNTT (Có Hợp Âm)',
                'category' => 'Kinh & Hát',
                'format' => 'MP3',
                'target' => 'Toàn Đoàn Thiếu Nhi & GLV',
                'size' => '12.8 MB',
                'author' => 'Ban Âm Nhạc TNTT',
                'downloads' => 680,
                'desc' => 'Tuyển tập 50 bài hát sinh hoạt, bài ca chính thức của các ngành Ấu, Thiếu, Nghĩa và Huynh Trưởng.',
                'content' => 'Bao gồm file nghe MP3 chất lượng cao và lời bài hát kèm hợp âm guitar/organ đệm hát trong giờ chào cờ và sinh hoạt.',
                'file_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'doc_id' => 'DOC09',
                'title' => 'Kinh Nguyện Hằng Ngày Dành Cho Thiếu Nhi Thánh Thể',
                'category' => 'Kinh & Hát',
                'format' => 'PDF',
                'target' => 'Toàn Thể Thiếu Nhi',
                'size' => '1.5 MB',
                'author' => 'Ban Phụng Vụ Tân Mỹ',
                'downloads' => 590,
                'desc' => 'Bản in bỏ túi các kinh nguyện sáng tối, kinh dâng ngày, kinh viếng Chúa, kinh dâng hoa và kinh bổn mạng.',
                'content' => 'Lời kinh chữ to, rõ ràng, dễ nhớ, có hình minh họa sinh động dành cho các em thiếu nhi học thuộc.',
                'file_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'doc_id' => 'DOC10',
                'title' => 'Biểu Mẫu Sổ Điểm Điện Tử & Bảng Điểm Lớp Giáo Lý 2026 - 2027',
                'category' => 'Biểu Mẫu',
                'format' => 'XLSX',
                'target' => 'Giáo Lý Viên & Ban Học Vụ',
                'size' => '1.2 MB',
                'author' => 'Ban Công Nghệ - Tân Mỹ',
                'downloads' => 350,
                'desc' => 'Mẫu bảng tính Excel chuẩn gồm đầy đủ 3 Sheet: Học Kỳ 1, Học Kỳ 2, Tổng Kết Cả Năm có tích hợp sẵn công thức tính điểm trung bình và xếp loại.',
                'content' => 'Biểu mẫu sẵn sàng nạp trực tiếp vào hệ thống web qua chức năng "Nhập Excel" của Sổ Điểm Điện Tử.',
                'file_url' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
